### ISSUE TITLE
Replace blizzard armory profile links with something better?

### ISSUE THREAD

**Issue by okwinza** [Exupery/pvpleaderboard#22]
Blizzard armory is pretty useless for PvP needs so It might be a good idea to link check-pvp or seramate profiles instead.

**Comment by Exupery** [comment]
It's not a bad idea, but the reality is third-party sites come and go and/or can change their URL structure on a whim (e.g. the resources page has been around for less than a year and even in that relatively short span I've had to remove several links to sites that went dead), linking to the armory provides more long-term stability and reliability (not to mention consistent user-experience since most players are familiar with the armory and most other third-party sites, including the above-mentioned check-pvp, have links to armory profiles).
